#ifndef DEMO_APP_SETTINGS_H
#define DEMO_APP_SETTINGS_H

// task priorities
#define INPUT_TASK_PRIORITY 3
#define RENDER_TASK_PRIORITY 2
#define WRITE_FRAME_TASK_PRIORITY 1

#endif  // DEMO_APP_SETTINGS_H